<script type="text/javascript">
//<![CDATA[
var MSG_ADDITEM_JS_ADDITEM = _("Tạo bản tài liệu");
var MSG_ADDITEM_JS_ADDMULTI = _("Add multiple items");
var MSG_ADDITEM_JS_MULTIVAL = _("Number of items to add");
var MSG_ADDITEM_JS_MULTI_UNIQUE_NOTE = _("NOTE: Fields listed in the \'UniqueItemsFields\' system preference will not be copied");
var MSG_ADDITEM_JS_SUBMITMULTI = _("Tạo");
var MSG_ADDITEM_JS_UPDATEITEM = _("Cập nhật tài liệu");
var MSG_ADDITEM_JS_EDIT = _("Chỉnh sửa");
var MSG_ADDITEM_JS_DELETE = _("Xóa");
var MSG_ADDITEM_JS_CLEAR = _("Xóa");
var MSG_ADDITEM_JS_CANT_RECEIVE_MORE_ITEMS = _("Bạn không thể nhận thêm tài liệu");
var MSG_ADDITEM_JS_IS_DUPLICATE = _("Tài liệu đã có");
var MSG_ADDITEM_JS_ALREADY_EXISTS_IN_DB = _("Đã có trong CSDL");
//]]>
</script>
