<tfoot>
 <tr>
 <td colspan="11" style="text-align: right; font-weight:bold;">Tổng số:</td>
 <td id="totaldue" style="text-align: right;">[% totaldue %]</td>
 <td id="totalfine" style="text-align: right;">[% finetotal %]</td>
 <td id="totalprice" style="text-align: right;">[% totalprice %]</td>
 <td colspan="3"><div class="date-select">
 <p><label for="newduedate">Gia hạn đến ngày:</label> <input type="text" size="12" id="newduedate" name="newduedate" value="[% newduedate %]" />
</p>
 <p><label for="exemptfine">Bỏ qua tiền phạt: <input type="checkbox" id="exemptfine" name="exemptfine" value="1" /></label></p></div>
 </td>
 </tr>
</tfoot>
