<div id="toolbar" class="btn-toolbar">
 <div class="btn-group"><a class="btn btn-default btn-sm" id="add_quote" href="#"><i class="fa fa-plus"></i> Tạo trích dẫn</a></div>
 <div class="btn-group"><a class="btn btn-default btn-sm" id="delete_quote" href="#"><i class="fa fa-trash"></i> Xóa trích dẫn</a></div>
 <div class="btn-group"><a class="btn btn-default btn-sm" id="import_quotes" href="/cgi-bin/koha/tools/quotes-upload.pl"><i class="fa fa-folder-open"></i> Nhập trích dẫn</a></div>
</div>
