<div id="toolbar" class="btn-toolbar" style="visibility: hidden; position: absolute">
 <div class="btn-group"><a class="btn btn-default btn-sm" id="save_quotes" href="#"><i class="fa fa-save"></i> Lưu trích dẫn</a></div>
 <div class="btn-group"><a class="btn btn-default btn-sm" id="delete_quote" href="#"><i class="fa fa-trash"></i> Xóa trích dẫn</a></div>
 <div class="btn-group"><a href="/cgi-bin/koha/tools/quotes-upload.pl" id="cancel_quotes" class="btn btn-default btn-sm"><i class="fa fa-remove"></i> Cancel import</a></div>
</div>
